name: Notify Team

on:
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Send Deployment Email
        uses: wesdevteam/maileraction@v1.2.3
        with:
          to: "obiifeanyidaniel@gmail.com"
          subject: "✅ Production Deployment Complete"
          text: "The deployment was completed successfully."
          html: "<p>The <strong>deployment</strong> to production was successful 🎉</p>"
        env:
          MAIL: "simon4gray@gmail.com"
          MAIL_PASSWORD: nsvb scpg ocdt zexl
          MAIL_HOST: smtp.gmail.com
          MAIL_PORT: 465
  
