- name: Send Email
  uses: wesdevteam/maileraction@v1.2.3
  with:
    server_address: ${{ secrets.MAIL_HOST }}
    server_port: 587
    username:  ${{ secrets.MAIL }}
    password: ${{ secrets.MAIL_PASSWORD }}
    subject: "Workflow Notification"
    body: "Your workflow finished running successfully."
    to: "user@example.com"
    from: "ci@example.com"
